# Generated by Django 5.1.7 on 2025-03-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='city_code',
            new_name='country_code',
        ),
    ]
