# Generated by Django 5.1.7 on 2025-03-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest',
            new_name='guests',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
