# Generated by Django 5.1.7 on 2025-04-01 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='favorite',
            new_name='favorited',
        ),
    ]
